### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by diatercinta** [prasathmani/tinyfilemanager#995] opened 2023-03-22 10:14 UTC
when i upload the tinyfilemanager.php it's detected malware

**Comment by smalos** [comment] 2023-03-22 10:19
Duplicate of

https://github.com/prasathmani/tinyfilemanager/issues/759
https://github.com/prasathmani/tinyfilemanager/issues/581

?

**Comment by diatercinta** [comment] 2023-03-22 11:02
> Duplicate of
> 
> #759 #581
> 
> ?

No

**Comment by diatercinta** [comment] 2023-03-22 22:19
> Using cPanel? https://support.cpanel.net/hc/en-us/articles/4967368771351-Editing-File-With-File-Manager-Fails-With-ERROR-BAILOUT-Malware-Detected-

But 
![image](https://user-images.githubusercontent.com/59323092/227051259-1655cc21-dd2c-405f-8a8e-123d87d20724.png)

**Comment by 3IceCube** [comment] 2023-03-23 16:38
@diatercinta @smalos @prasathmani 
Ok, it worked. I don't know how and why but it worked.
Earlier, immunify360 in cPanel was marking and rejecting the tinyfilemanager.php as a malware when uploaded.
What I have done is, I removed the line **6** in the .php file.

Line containing:-

 * H3K | Tiny File Manager V2.5.3

Then saved and uploaded the file as usual. That's it.

**Comment by diatercinta** [comment] 2023-03-23 20:34
> @diatercinta @smalos @prasathmani Ok, it worked. I don't know how and why but it worked. Earlier, immunify360 in cPanel was marking and rejecting the tinyfilemanager.php as a malware when uploaded. What I have done is, I removed the line **6** in the .php file.
> 
> Line containing:-
> 
> * H3K | Tiny File Manager V2.5.3
> 
> Then saved and uploaded the file as usual. That's it.

Thanks it's Solved

**Closed** 2023-03-23 20:34 UTC
Labels: duplicate

**Comment by divinity76** [comment] 2023-04-10 16:17
basically, some actual malware installs tfm to allow the malware operators file access after infection. then antivirus heuristics thought tfm itself was malware (because it is installed by malware)

the correct course of action is probably to complain to the antivirus vendor.

**Comment by uploadkeeper** [comment] 2024-05-01 20:01
your website is not working
