### ISSUE TITLE
[Maximum file upload size] seems to be unused, right?

### ISSUE THREAD

**Issue by MoonLord-LM** [prasathmani/tinyfilemanager#846] opened 2022-08-28 19:18 UTC
```
// Maximum file upload size
// Increase the following values in php.ini to work properly
// memory_limit, upload_max_filesize, post_max_size
$max_upload_size_bytes = 5000;

// max upload file size
define('MAX_UPLOAD_SIZE', $max_upload_size_bytes);
```

**Comment by smalos** [comment] 2022-09-07 12:29
Yes, it looks like.

**Comment by redherring917b** [comment] 2022-10-17 18:00
Wanted to add that there may possibly be a filetype (aka extension) related angle to this oddity, where some filetypes are handled properly per the limits set while others are not - this still needs to be confirmed.

Thanks.

**Comment by redherring917b** [comment] 2022-10-18 21:08
Wanted to comment that we discovered that the following setting in the tiny file manager script that configures Dropzone

maxFilesize: 10000000000

is, despite the default size, actually in MB.  And as such, changing this value to simply 5 successfully restricts file uploads to 5MB's.  

While this seems to resolve the issue, it is still odd as it means that tiny file manager is ignoring its max file size setting ($max_upload_size_bytes) and using this one for dropzone. i'd still like an answer on that... why the $max_upload_size_bytes seems to be ignored.

Thanks.

**Comment by prasathmani** [comment] 2022-11-19 20:02
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).

**Closed by prasathmani** 2022-11-19 20:02 UTC
